version: "3"
services:
  db:
    image: mysql:5.7
    container_name: tickers-db
    environment:
      MYSQL_USER: chocopi
      MYSQL_DATABASE: chocopi
      MYSQL_PASSWORD: pass
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./docker/db/data:/var/lib/mysql
      - ./docker/db/sql:/docker-entrypoint-initdb.d
    ports:
      - 3306:3306
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci

